'use client'
import { useState } from 'react'
import { Search, Sparkles, BookOpen, Code2, FileText, BrainCircuit, ArrowRight, Upload, ShieldCheck, Cpu, Leaf, Activity } from 'lucide-react'
const cards=[['AI Lab','Chat, vision, document analysis and agent workflows.','/ai','BrainCircuit'],['Knowledge Base','Turn PDFs, books, notes and projects into searchable knowledge.','/knowledge','BookOpen'],['Problem Solver','Maths, science, coding and research with step-by-step reasoning.','/solve','Sparkles'],['Code Lab','Debug, explain, generate and review code.','/code','Code2'],['Articles & Books','Create, review, preview and publish technical knowledge.','/articles','FileText'],['Live Projects','Connect IoT, agriculture and real-time dashboards.','/projects','Activity']]
export default function Home(){const [q,setQ]=useState('');return <main>
<header className="nav"><div className="brand"><span className="logo">N</span>NOVA <b>HUB</b></div><nav><a>Explore</a><a>Articles</a><a>Books</a><a>Projects</a><a>AI Lab</a></nav><button className="ghost">Sign in</button></header>
<section className="hero"><div className="glow"/><div className="eyebrow"><Sparkles size={15}/> NEXT-GENERATION KNOWLEDGE PLATFORM</div><h1>Think. Build.<br/><span>Discover more.</span></h1><p>One intelligent workspace for knowledge, documents, coding, research, projects and advanced AI problem solving.</p><div className="search"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask NOVA or search knowledge..."/><kbd>⌘ K</kbd></div><div className="actions"><button className="primary"><Sparkles size={18}/> Open AI Lab</button><button className="secondary">Explore platform <ArrowRight size={17}/></button></div></section>
<section className="stats"><div><strong>AI</strong><span>Multi-agent engine</span></div><div><strong>∞</strong><span>Knowledge capacity</span></div><div><strong>24/7</strong><span>Project intelligence</span></div><div><strong>1</strong><span>Unified workspace</span></div></section>
<section className="section"><div className="sectionHead"><div><div className="eyebrow">PLATFORM</div><h2>Everything you need to <span>solve & create.</span></h2></div><button className="textBtn">View all <ArrowRight size={16}/></button></div><div className="grid">{cards.map(([title,desc,href,icon])=><div className="card" key={title}><div className="icon">{icon==='BrainCircuit'?<BrainCircuit/>:icon==='BookOpen'?<BookOpen/>:icon==='Sparkles'?<Sparkles/>:icon==='Code2'?<Code2/>:icon==='FileText'?<FileText/>:<Activity/>}</div><h3>{title}</h3><p>{desc}</p><a href={href}>Open <ArrowRight size={15}/></a></div>)}</div></section>
<section className="aiPanel"><div><div className="eyebrow"><Cpu size={15}/> INTELLIGENCE ENGINE</div><h2>Your knowledge.<br/><span>Your AI.</span></h2><p>Upload a document, image, codebase or research material. NOVA can understand it, search it, compare it and help you turn it into something useful.</p><div className="chips"><span><Upload size={14}/> PDF / DOCX</span><span><ShieldCheck size={14}/> Private knowledge</span><span><Leaf size={14}/> Agriculture ready</span></div></div><div className="terminal"><div className="dots">● ● ●</div><div><i>nova</i> analyze <b>uploaded_book.pdf</b></div><div className="muted">→ 18 chapters indexed</div><div className="muted">→ 642 knowledge chunks</div><div className="muted">→ semantic search ready</div><div className="success">✓ Knowledge engine online</div></div></section>
<footer><div className="brand"><span className="logo">N</span>NOVA HUB</div><span>AI Knowledge • Problem Solving • Projects</span></footer></main>}
