'use client'
import { useEffect, useState } from 'react'
import { BookOpen, Search, FileText, Database, ShieldCheck, Loader2 } from 'lucide-react'

type Item = { id:string; title:string; type:string; body:string; status:string; topics:string[]; updated_at:string }

export default function Knowledge(){
  const [items,setItems]=useState<Item[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  async function load(query=''){ setLoading(true); setError(''); try { const res=await fetch(`/api/content${query?`?q=${encodeURIComponent(query)}`:''}`,{cache:'no-store'}); const data=await res.json(); if(!res.ok) throw new Error(data?.error||'Could not load knowledge'); setItems(data.items||[]) } catch(e){setError(e instanceof Error?e.message:'Could not load knowledge')} finally{setLoading(false)} }
  useEffect(()=>{load()},[])
  return <main><header className="nav"><a className="brand" href="/"><span className="logo">N</span>NOVA <b>KNOWLEDGE</b></a><nav><a href="/ai">AI Lab</a><a href="/articles">Articles</a><a href="/projects">Projects</a></nav><a className="ghost" href="/admin">Admin</a></header><section className="workspace"><div className="workspaceHead"><div><div className="eyebrow"><BookOpen size={15}/> KNOWLEDGE BASE</div><h1>Your private knowledge engine.</h1><p>Live published content from NOVA's Supabase knowledge layer.</p></div></div><div className="knowledgeStats"><div><Database/> <b>{items.length}</b><span>published items loaded</span></div><div><Search/> <b>Live</b><span>Supabase search</span></div><div><ShieldCheck/> <b>RLS</b><span>database security</span></div></div><div className="search wide"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load(q)}} placeholder="Search published knowledge..."/><button className="secondary" onClick={()=>load(q)}>{loading?<Loader2 className="spin" size={16}/>: 'Search'}</button></div>{error&&<div className="card"><b>Knowledge connection</b><p>{error}</p></div>}<div className="list">{items.map(item=><div className="row" key={item.id}><div className="fileIcon"><FileText/></div><div><b>{item.title}</b><span>{item.type} • {(item.topics||[]).join(', ')||'No topics'}</span></div><em>{item.status}</em></div>)}{!loading&&!error&&!items.length&&<div className="card"><b>No published content yet.</b><p>Create and publish an article in the publishing module after Supabase/Auth is configured.</p></div>}{loading&&<div className="card"><Loader2 className="spin"/> Loading knowledge…</div>}</div></section></main>
}
