'use client'
import { useEffect, useMemo, useState } from 'react'
import { Activity, Cpu, Leaf, Wifi, Database, Bell, Loader2 } from 'lucide-react'

type Reading={id:number;project_id:string;device_id:string;moisture:number|null;temperature:number|null;humidity:number|null;recorded_at:string}
export default function Projects(){
 const [readings,setReadings]=useState<Reading[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true)
 async function load(){try{const r=await fetch('/api/sensors',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d?.error||'Telemetry unavailable');setReadings(d.readings||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Telemetry unavailable')}finally{setLoading(false)}}
 useEffect(()=>{load();const id=setInterval(load,5000);return()=>clearInterval(id)},[])
 const latest=readings[0]; const metrics=useMemo(()=>[['Soil moisture',latest?.moisture!=null?`${latest.moisture}%`:'--',latest?'Live sensor':'Waiting for ESP32'],['Temperature',latest?.temperature!=null?`${latest.temperature}°C`:'--',latest?'Live sensor':'Waiting for sensor'],['Humidity',latest?.humidity!=null?`${latest.humidity}%`:'--',latest?'Live sensor':'Waiting for sensor'],['Device status',latest?'Online':'Offline',latest?latest.device_id:'Connect device']], [latest])
 return <main><header className="nav"><a className="brand" href="/"><span className="logo">N</span>NOVA <b>PROJECTS</b></a><nav><a href="/projects">Projects</a><a href="/knowledge">Knowledge</a><a href="/ai">AI Lab</a></nav><a className="ghost" href="/">Home</a></header><section className="workspace"><div className="workspaceHead"><div><div className="eyebrow"><Activity size={15}/> LIVE PROJECTS</div><h1>Project intelligence dashboard.</h1><p>Live ESP32/IoT telemetry from the NOVA Supabase sensor layer.</p></div><button className="primary" onClick={load}><Wifi size={16}/> Refresh</button></div><div className="knowledgeStats">{metrics.map(([a,b,c])=><div key={a}><Cpu/><b>{b}</b><span>{a} • {c}</span></div>)}</div>{error&&<div className="card"><b>Telemetry connection</b><p>{error}</p><small>For private sensor rows, configure SUPABASE_SECRET_KEY on the server or connect user authentication.</small></div>}{loading&&<div className="card"><Loader2 className="spin"/> Loading telemetry…</div>}<div className="grid"><div className="card"><Leaf/><h3>AgriBot</h3><p>Soil moisture, temperature, humidity, camera observations and farmer alerts.</p><a href="/projects">Live dashboard →</a></div><div className="card"><Database/><h3>Knowledge telemetry</h3><p>{readings.length} latest sensor readings available to the live dashboard.</p><a href="/knowledge">View knowledge →</a></div><div className="card"><Bell/><h3>Alerts</h3><p>Threshold-based and AI-generated notifications can use the same readings.</p><a href="/ai">Analyze with NOVA →</a></div></div>{latest&&<div className="card" style={{marginTop:24}}><b>Latest reading</b><p>Device <strong>{latest.device_id}</strong> • {new Date(latest.recorded_at).toLocaleString()}</p><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(latest,null,2)}</pre></div>}</section></main>
}
