'use client'

import { useRef, useState } from 'react'
import { BrainCircuit, Send, Paperclip, Sparkles, X } from 'lucide-react'

type Message = { role: 'user' | 'assistant'; content: string }
const agents = ['General AI', 'Document Analyst', 'Vision Agent', 'Research Agent', 'Coding Agent', 'Agriculture Agent']

export default function AI() {
  const [q,setQ]=useState(''); const [messages,setMessages]=useState<Message[]>([]); const [agent,setAgent]=useState('General AI'); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [image,setImage]=useState<{data:string;mime:string;name:string}|null>(null); const inputRef=useRef<HTMLInputElement>(null)
  async function ask(text=q){ const prompt=text.trim(); if(!prompt||loading)return; const next=[...messages,{role:'user' as const,content:image?`${prompt}\n[Image: ${image.name}]`:prompt}]; setMessages(next); setQ(''); setError(''); setLoading(true); try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:prompt,history:messages,agent,imageData:image?.data,imageMimeType:image?.mime})});const d=await r.json();if(!r.ok)throw new Error(d?.error||'NOVA could not answer.');setMessages([...next,{role:'assistant',content:d.answer}]);setImage(null)}catch(e){setError(e instanceof Error?e.message:'NOVA could not answer.')}finally{setLoading(false)} }
  function attach(file:File){if(!file.type.startsWith('image/')){setError('Please choose an image file.');return} if(file.size>5*1024*1024){setError('Image must be 5 MB or smaller.');return} const reader=new FileReader();reader.onload=()=>{const raw=String(reader.result||'');setImage({data:raw.split(',')[1]||'',mime:file.type,name:file.name});setError('')};reader.readAsDataURL(file)}
  return <main><header className="nav"><a className="brand" href="/"><span className="logo">N</span>NOVA <b>AI</b></a><nav><a href="/">Home</a><a href="/knowledge">Knowledge</a><a href="/solve">Solve</a></nav><a className="ghost" href="/admin">Admin</a></header><section className="workspace"><div className="workspaceHead"><div><div className="eyebrow"><BrainCircuit size={15}/> AI LAB</div><h1>Ask NOVA anything.</h1><p>Live AI for chat, problem solving, research, coding, agriculture and image understanding.</p></div><div className="status"><span/>{loading?'Thinking…':'Engine ready'}</div></div><div className="agentGrid">{agents.map(name=><button key={name} className={agent===name?'active':''} onClick={()=>{setAgent(name);setQ(name+': ')}}><Sparkles size={16}/>{name}</button>)}</div><div className="chat">{messages.length===0?<div className="empty"><BrainCircuit size={46}/><h2>What are you solving today?</h2><p>Ask a question or attach an image and NOVA will generate a real AI response.</p></div>:messages.map((m,i)=><div className={`bubble ${m.role}`} key={`${m.role}-${i}`}><b>{m.role==='user'?'You':'NOVA'}</b><div style={{whiteSpace:'pre-wrap'}}>{m.content}</div></div>)}{loading&&<div className="bubble assistant"><b>NOVA</b><div>Thinking…</div></div>}</div>{error&&<div className="warning" style={{margin:'12px 0'}}>{error}</div>}{image&&<div className="card" style={{margin:'12px 0',display:'flex',justifyContent:'space-between',alignItems:'center'}}><span>Attached: {image.name}</span><button className="secondary" onClick={()=>setImage(null)}><X size={15}/> Remove</button></div>}<div className="composer"><button title="Attach image" onClick={()=>inputRef.current?.click()} disabled={loading}><Paperclip size={19}/></button><input ref={inputRef} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];if(f)attach(f);e.currentTarget.value=''}}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask()}} placeholder="Ask NOVA..." disabled={loading}/><button className="primary" onClick={()=>ask()} disabled={loading||!q.trim()}><Send size={17}/></button></div></section></main>
}
